# XTL - the eXternalization Template Library (sample code)
# by Jose' Orlando Pereira, Universidade do Minho
# 
# jop@di.uminho.pt - http://gsd.di.uminho.pt/~jop
# 
# $Id: Makefile,v 1.1 2005/02/24 05:24:07 philgrim Exp $


all:
	make -C smart
	make -C auto
	make -C graph
	make -C tests
	make -C bench

clean:
	make -C smart clean
	make -C auto clean
	make -C graph clean
	make -C tests clean
	make -C bench clean


